/*	Definition of the Text Resources used in Space Invaders

	Prefix: TR_
	@author Ramon Molla
	@version 07/2014
*/

#ifndef TR_TEXT_RESOURCES
#define TR_TEXT_RESOURCES

#define TR_MAX_LOG_NAME				  32
#define TR_MAX_TEXT_RESOURCES		1010	//Maximum amount of text resources available in this game version

//Si_Basecode
#define TR_BASECODE_INTERNET_ERROR				1
#define TR_BASECODE_INTERNET_CONECTION_WARNING	2
#define TR_BASECODE_INTERNET_CONECTION_WARNING2	3

#define TR_BASECODE_WM_HSCROLL1					11
#define TR_BASECODE_WM_HSCROLL2					12
#define TR_BASECODE_ERROR_CREATE_EDIT_CTRL		13
#define TR_BASECODE_ERROR_CREATE_EDIT_CTRL2		14

#define TR_BASECODE_MIPMAP_TEXTURES				21
#define TR_BASECODE_MIPMAP_TEXTURES2			22
#define TR_BASECODE_VERTICAL_SYNCH				23
#define TR_BASECODE_VERTICAL_SYNCH2				24
#define TR_BASECODE_MUSIC_STREAM				25
#define TR_BASECODE_MUSIC_STREAM2				26
#define TR_BASECODE_BILLBOARDING				27
#define TR_BASECODE_BILLBOARDING2				28
#define TR_BASECODE_ANTI_ALIASING				29
#define TR_BASECODE_ANTI_ALIASING2				30
#define TR_BASECODE_ANTI_ALIASING_MODE			31
#define TR_BASECODE_ANTI_ALIASING_MODE2			32
#define TR_BASECODE_TRACKMOUSE_EVENT_FAILED		33
#define TR_BASECODE_ERROR_CREATING_OPENGL		34
#define TR_BASECODE_DIAL_UP						35
#define TR_BASECODE_CUSTOM						36
#define TR_BASECODE_SOUND_INIT_ERROR			37

#define TR_BASECODE_INIT_COMMON_FAILED			51
#define TR_BASECODE_ERROR_REGISTER_WCLASS		52
#define TR_BASECODE_ERROR_REGISTER_WCLASS2		53
#define TR_BASECODE_START						54
#define TR_BASECODE_ERROR_CREATING_OPENGL2		55


//Si_Functions
#define TR_FUNCTIONS_STREAM_URL_EMPTY			101
#define TR_FUNCTIONS_NUMBER_ENTRIES_NOFOUND		102
#define TR_FUNCTIONS_NUMERIC_ENTRIES_NOFOUND	103
#define TR_FUNCTIONS_ERROR_ALLOCATE_MEM			104
#define TR_FUNCTIONS_ERROR_ALLOCATE_MEM2		105
#define TR_FUNCTIONS_ERROR_ALLOCATE_MEM3		106

#define TR_FUNCTIONS_DISPLAY					111
#define TR_FUNCTIONS_QUICK_FULLSCREEN			112
#define TR_FUNCTIONS_FULLSCREEN					113
#define TR_FUNCTIONS_WINDOWS					114
#define TR_FUNCTIONS_MISC						115
#define TR_FUNCTIONS_VSYNC						116
#define TR_FUNCTIONS_STREAMING					117
#define TR_FUNCTIONS_QUALITY					118
#define TR_FUNCTIONS_ANTI_ALIASING				119
#define TR_FUNCTIONS_BILLBOARDING				120
#define TR_FUNCTIONS_MIP_MAP_TEXTURES			121
#define TR_FUNCTIONS_DIAL_UP					123
#define TR_FUNCTIONS_CUSTOM						124

#define TR_FUNCTIONS_WEB_PAGE					151
#define TR_FUNCTIONS_FORUM						152
#define TR_FUNCTIONS_WIKIK_KEYB					153
#define TR_FUNCTIONS_CLOSE_WINDOW				154
#define TR_FUNCTIONS_CUSSTOM_URL				155
#define TR_FUNCTIONS_INSERT_PLAAYLIST			156
#define TR_FUNCTIONS_INSERT_PLAAYLIST2			157


//game
#define TR_GAME_LOADING_LEVEL					201

#define TR_GAME_LOADING_SAVED_LEVEL				211

#define TR_GAME_DATE							221
#define TR_GAME_LOADING_SOUNDS					222
#define TR_GAME_LOADING_INIT_FILE				223
#define	TR_GAME_SAVED_GAME_DETECTED		 		224
#define TR_GAME_LOAD_GAME						225
#define TR_GAME_READ_SAVED_GAME					226
#define TR_GAME_READ_FIRST_LEVEL				227
#define TR_GAME_GEN_DEFAULT_NAVY				228
#define TR_GAME_SHOOTS							229
#define TR_GAME_ENV_VAR							230
#define TR_GAME_SOUND_ERROR						231

#define TR_GAME_LOADING_TEXT					241
#define TR_GAME_LOADING_MESHES					242
#define TR_GAME_ERROR_3D_LOAD					243
#define TR_GAME_END_LOADING						244


//Si_Main
#define TR_MAIN_MAIN_LOADING_LEVEL				301
#define TR_MAIN_ERROR							302
#define TR_MAIN_ENTER_IMMORTAL_MODE				303
#define TR_MAIN_ENTER_MORTAL_MODE				304
#define TR_MAIN_PUT_MP3_FILES					305
#define TR_MAIN_CHOOSE_ANTI_ALIASING			306
#define TR_MAIN_ANTI_ALIASING_NOUSED			307
#define TR_MAIN_ANTI_ALIASING_ON				308
#define TR_MAIN_ANTI_ALIASING_OFF				309
#define TR_MAIN_SWAP_INTERV_NOAVAILABLE			310
#define TR_MAIN_VERT_SYNC_ON					311
#define TR_MAIN_VERT_SYNC_OFF					312

#define TR_MAIN_SONIDO							321
#define TR_MAIN_AUDIO							322
#define TR_MAIN_TIME							323
#define TR_MAIN_ANGLE							324
#define TR_MAIN_CAMERA_ANGLE					325
#define TR_MAIN_EXIT_ESC						326
#define TR_MAIN_MOUSE_ROTATION					327
#define TR_MAIN_MUSIC_ON						328
#define TR_MAIN_MUSIC_OFF						329
#define TR_MAIN_BACKGROUND						330
#define TR_MAIN_REPLACE_CAM						331
#define TR_MAIN_HIDE_TEXT						332
#define TR_MAIN_ZOOM							333
#define TR_MAIN_HEIGHT							334
#define TR_MAIN_WIDTH							335
#define TR_MAIN_SPACE_MUSIC						336

#define TR_MAIN_ENTERING_LEVEL					351
#define TR_MAIN_YOU_WIN							352
#define TR_MAIN_GAME_OVER						353
#define TR_MAIN_YOU_LOSE						354

#define TR_MAIN_ERROR_ZIK						361


//InitializationParser
#define TR_INIT_PARSER_CHARACTER_TYPE			401
#define TR_INIT_PARSER_CHARACTER_TYPE2			402

#define TR_INIT_PARSER_START_INIT				411

#define TR_INIT_PARSER_START_TAG				421
#define TR_INIT_PARSER_FIRST_TAG				422
#define TR_INIT_PARSER_TAG_ERROR11				423
#define TR_INIT_PARSER_TAG_ERROR12				424
#define TR_INIT_PARSER_TAG_ERROR21				425
#define TR_INIT_PARSER_TAG_ERROR22				426
#define TR_INIT_PARSER_TAG_ERROR31				427
#define TR_INIT_PARSER_TAG_ERROR32				428
#define TR_INIT_PARSER_TAG_ERROR41				429
#define TR_INIT_PARSER_TAG_ERROR42				430
#define TR_INIT_PARSER_WARNING					431
#define TR_INIT_PARSER_WARNING2					432
#define TR_INIT_PARSER_WARNING3					433
#define TR_INIT_PARSER_WARNING4					434
#define TR_INIT_PARSER_WARNING5					435
#define TR_INIT_PARSER_WARNING61				436
#define TR_INIT_PARSER_WARNING62				437
#define TR_INIT_PARSER_WARNING7					438

#define TR_INIT_PARSER_ERROR_CLOSING			441

#define TR_INIT_PARSER_END_TAG					451
#define TR_INIT_PARSER_CLOSE_TAG_UNK			452
#define TR_INIT_PARSER_CLOSE_TAG_NO_CORRESP1	453
#define TR_INIT_PARSER_CLOSE_TAG_NO_CORRESP2	454

#define TR_INIT_PARSER_TEXT						461
#define TR_INIT_PARSER_MAX_LIFE_ERROR11			462
#define TR_INIT_PARSER_MAX_LIFE_ERROR12			463
#define TR_INIT_PARSER_MAX_LIFE_ERROR21			464
#define TR_INIT_PARSER_MAX_LIFE_ERROR22			465
#define TR_INIT_PARSER_BAD_FILE					466
#define TR_INIT_PARSER_INIT_WARNING1			467
#define TR_INIT_PARSER_INIT_WARNING2			468
#define TR_INIT_PARSER_BAD_VERSION1				469
#define TR_INIT_PARSER_BAD_VERSION2				470

#define TR_INIT_PARSER_COMMENTS					481

#define TR_INIT_PARSER_END_INTERP				491

//texturesManager
#define TR_TEXT_MANAGER_LOAD_TEXT				501
#define TR_TEXT_MANAGER_LOAD_TEXT_100			502

//texture
#define TR_TEXT_ERROR_PNG						551

//Main menu options
#define TR_MENU_WINDOW_GAME						600
#define TR_MENU_WINDOW_LEVEL					610
#define TR_MENU_WINDOW_CONFIGURATION			620
#define TR_MENU_WINDOW_HELP						630
#define TR_MENU_WINDOW_ABOUT					640

#define TR_MENU_WINDOW_START_GAME				611
#define TR_MENU_WINDOW_EXIT_GAME				612

#define TR_TAG_OK								711
#define TR_TAG_MARKED							712
#define TR_TAG_CUSTOMIZED						713
#define TR_TAG_HOMEPAGE							714
#define TR_TAG_FORUM							715
#define TR_TAG_BUTTON_CLOSE						717
#define TR_TAG_CUSTOM1							718
#define TR_TAG_CUSTOM2							719

#define TR_TAG_SHOW_LANG					   750
#define TR_TAG_LANGUAGE						   751
#define TR_TAG_CHANGE_LANGUAGE				   752
#define TR_TAG_MESSAGES						   753
#define TR_TAG_ACCEPT						   754
#define TR_TAG_MSG_LANGUAGE					   755

#define	TR_MAX_TR							   800
#endif